<?php

namespace Database\Seeders;

use App\Models\Venue;
use Illuminate\Database\Seeder;

class VenueSeeder extends Seeder
{
    public function run(): void
    {
        $venues = [
            [
                'name'           => 'Lapangan Futsal Senayan Sport',
                'address'        => 'Jl. Asia Afrika, Gelora, Tanah Abang, Jakarta Pusat',
                'city'           => 'Jakarta',
                'latitude'       => -6.2183,
                'longitude'      => 106.8017,
                'price_per_hour' => 200000,
                'contact_phone'  => '021-5731234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Arena Futsal Kemayoran',
                'address'        => 'Jl. Benyamin Sueb, Kemayoran, Jakarta Pusat',
                'city'           => 'Jakarta',
                'latitude'       => -6.1594,
                'longitude'      => 106.8451,
                'price_per_hour' => 175000,
                'contact_phone'  => '021-6541234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Futsal Planet Bekasi',
                'address'        => 'Jl. Ahmad Yani No. 12, Bekasi Timur',
                'city'           => 'Bekasi',
                'latitude'       => -6.2383,
                'longitude'      => 107.0122,
                'price_per_hour' => 150000,
                'contact_phone'  => '021-8841234',
                'is_active'      => true,
            ],
            [
                'name'           => 'GOR Futsal Depok Jaya',
                'address'        => 'Jl. Margonda Raya No. 55, Depok',
                'city'           => 'Depok',
                'latitude'       => -6.3794,
                'longitude'      => 106.8314,
                'price_per_hour' => 130000,
                'contact_phone'  => '021-7771234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Futsal Kingdom Tangerang',
                'address'        => 'Jl. MH Thamrin No. 8, Tangerang',
                'city'           => 'Tangerang',
                'latitude'       => -6.1783,
                'longitude'      => 106.6297,
                'price_per_hour' => 160000,
                'contact_phone'  => '021-5521234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Lapangan Futsal BSD',
                'address'        => 'Jl. Pahlawan Seribu, BSD City, Tangerang Selatan',
                'city'           => 'Tangerang Selatan',
                'latitude'       => -6.3016,
                'longitude'      => 106.6529,
                'price_per_hour' => 180000,
                'contact_phone'  => '021-5381234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Futsal Center Bogor',
                'address'        => 'Jl. Pajajaran No. 30, Bogor Tengah',
                'city'           => 'Bogor',
                'latitude'       => -6.5971,
                'longitude'      => 106.7960,
                'price_per_hour' => 120000,
                'contact_phone'  => '0251-8341234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Arena Futsal Grogol (Nonaktif)',
                'address'        => 'Jl. S. Parman No. 3, Grogol, Jakarta Barat',
                'city'           => 'Jakarta',
                'latitude'       => -6.1676,
                'longitude'      => 106.7886,
                'price_per_hour' => 140000,
                'contact_phone'  => '021-5671234',
                'is_active'      => false,
            ],
            [
                'name'           => 'Viva Futsal Malang',
                'address'        => 'Jl. Bunga Andong, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'city'           => 'Malang',
                'latitude'       => -7.9449,
                'longitude'      => 112.6220,
                'price_per_hour' => 120000,
                'contact_phone'  => '0341-484377',
                'is_active'      => true,
            ],
            [
                'name'           => 'Angkasa Futsal Malang',
                'address'        => 'Jl. Papa Kuning No.40, Tulusrejo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'city'           => 'Malang',
                'latitude'       => -7.9410,
                'longitude'      => 112.6360,
                'price_per_hour' => 100000,
                'contact_phone'  => '0823-3520-6077',
                'is_active'      => true,
            ],
            [
                'name'           => 'Lapangan Futsal UIN Malang',
                'address'        => 'Kampus 1 UIN Maulana Malik Ibrahim Malang, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9517,
                'longitude'      => 112.6071,
                'price_per_hour' => 100000,
                'contact_phone'  => '-',
                'is_active'      => true,
            ],
            [
                'name'           => 'Buana Futsal Malang',
                'address'        => 'Tlogosari 36 A, Kota Malang, Jawa Timur',
                'city'           => 'Malang',
                'latitude'       => -7.9870,
                'longitude'      => 112.6350,
                'price_per_hour' => 100000,
                'contact_phone'  => '0341-7744778',
                'is_active'      => true,
            ],
            [
                'name'           => 'Bima Sakti Futsal Malang',
                'address'        => 'Sukun, Kota Malang, Jawa Timur 65147',
                'city'           => 'Malang',
                'latitude'       => -7.9970,
                'longitude'      => 112.6110,
                'price_per_hour' => 90000,
                'contact_phone'  => '-',
                'is_active'      => true,
            ],
            [
                'name'           => 'Champion Futsal Malang',
                'address'        => 'Jl. Soekarno Hatta No.9, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'city'           => 'Malang',
                'latitude'       => -7.9384,
                'longitude'      => 112.6212,
                'price_per_hour' => 130000,
                'contact_phone'  => '0341-477123',
                'is_active'      => true,
            ],
            [
                'name'           => 'Galaxy Futsal Malang',
                'address'        => 'Jl. Sukarno Hatta, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141',
                'city'           => 'Malang',
                'latitude'       => -7.9402,
                'longitude'      => 112.6188,
                'price_per_hour' => 110000,
                'contact_phone'  => '0341-401234',
                'is_active'      => true,
            ],
            [
                'name'           => 'Mitra Futsal Malang',
                'address'        => 'Jl. Tlogomas No.24, Tlogomas, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'city'           => 'Malang',
                'latitude'       => -7.9335,
                'longitude'      => 112.5972,
                'price_per_hour' => 100000,
                'contact_phone'  => '0341-565123',
                'is_active'      => true,
            ],
            [
                'name'           => 'Score Futsal Malang',
                'address'        => 'Jl. Bendungan Sutami No.18, Sumbersari, Kec. Lowokwaru, Kota Malang, Jawa Timur 65145',
                'city'           => 'Malang',
                'latitude'       => -7.9573,
                'longitude'      => 112.6101,
                'price_per_hour' => 120000,
                'contact_phone'  => '0341-551789',
                'is_active'      => true,
            ],
            [
                'name'           => 'Araya Futsal Malang',
                'address'        => 'Jl. Simpang Borobudur, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65142',
                'city'           => 'Malang',
                'latitude'       => -7.9298,
                'longitude'      => 112.6404,
                'price_per_hour' => 140000,
                'contact_phone'  => '0341-491456',
                'is_active'      => true,
            ],
            [
                'name'           => 'Mandala Futsal Malang',
                'address'        => 'Jl. Danau Toba, Sawojajar, Kec. Kedungkandang, Kota Malang, Jawa Timur 65139',
                'city'           => 'Malang',
                'latitude'       => -7.9762,
                'longitude'      => 112.6582,
                'price_per_hour' => 95000,
                'contact_phone'  => '0341-712345',
                'is_active'      => true,
            ],
            [
                'name'           => 'D\'Pin Futsal Malang',
                'address'        => 'Jl. Raya Tlogomas No.45, Tlogomas, Kec. Lowokwaru, Kota Malang, Jawa Timur 65144',
                'city'           => 'Malang',
                'latitude'       => -7.9311,
                'longitude'      => 112.6005,
                'price_per_hour' => 105000,
                'contact_phone'  => '0852-3456-7890',
                'is_active'      => true,
            ],
        ];

        foreach ($venues as $venue) {
            Venue::updateOrCreate(
                ['name' => $venue['name']],
                $venue
            );
        }
    }
}
